spring.application.name=SAE
# Port du serveur
server.port=8080

# Database H2 (in-memory) - The name 'saedb' is important for Swagger
spring.datasource.url=jdbc:h2:mem:saedb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate - Auto-create tables from entities
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Security - Fixed credentials for tests
# Use these on http://localhost:8080/login
spring.security.user.name=admin
spring.security.user.password=admin
# Cle secrete
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Expiration en millisecondes 24h
jwt.expiration=86400000
